title: DARLINGTON OBUKOWHO
logo: Datalogo.jpg
description: Data Analyst with hands-on experience in SQL, Excel, and Power BI. Skilled in data cleaning, data analysis, data visualization, dashboard development, and reporting.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
