title: Darlington Obukowho
logo: Datalogo.jpg
description: Data analyst with experience using microsoft excel for report automation, sql for data manipulation and interrogation and power bi for business insight.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
